### ISSUE TITLE
Support for manually calling .setChecked() function

### ISSUE THREAD

**Issue by Spirit4449** [luandiasrj/QToggle_-_Advanced_QCheckbox_for_PyQT6#1]
If you want to set the state of the toggle you can do so by running .setChecked(True) on it. But this doesn't update the colors

**Comment by luandiasrj** [comment]
It seems that the error occurred because the setChecked method sends a stateChanged signal, automatically activating the animation by taking the default color before the component is even built with the custom colors.

I fixed it by simply setting a condition to activate the animation only if the user interacts with the component.

I'll be happy to hear that the fix worked.

Best regards!

**Comment by Spirit4449** [comment]
Thank you!!
